### ISSUE TITLE
errror, not starting

### ISSUE THREAD

**Issue by adrian-rt** [SpiderLabs/beef_injection_framework#5]
i always get this error:

ruby shank.rb  192.168.1.0/32

/var/lib/gems/1.9.2/gems/gems/packetfu-1.1.6/lib/packetfu/utils.rb:92:in `whoami?': uninitialized constant PacketFu::Capture (NameError)
    from shank.rb:120:in`initialize'
    from shank.rb:284:in `new'
    from shank.rb:284:in`<main>'

of if i start with just a single ip 192.168.1.0 or 192.168.1.0/31.
The idea is that i don't want to arp spoof the entire network .

**Comment by adrian-rt** [comment]
i tried to install pcaprub:

gem1.9.2 install --user-install pcaprub
/usr/lib/ruby/1.9.2/rubygems/installer.rb:135: warning: Insecure world writable dir /root/.gem/ruby/1.9.2/bin in PATH, mode 040777
Building native extensions.  This could take a while...
Successfully installed pcaprub-0.11.3
1 gem installed
Installing ri documentation for pcaprub-0.11.3...
Installing RDoc documentation for pcaprub-0.11.3...

but:

gem1.9.2 which pcaprub
ERROR:  Can't find ruby library file or shared library pcaprub

**Comment by adrian-rt** [comment]
solved it in the end it worked with gem install pcaprub
