### ISSUE TITLE
install beef_injection_framework

### ISSUE THREAD

**Issue by badatel** [SpiderLabs/beef_injection_framework#7]
Hello, i wanna install this tool. Have already instaled beef. (just changed port to 80)
After that used this commands: 
gem install packetfu
gem install json
gem install rest_client

after that used: https://github.com/SpiderLabs/beef_injection_framework.git

If i wanted start shank.rb get this error:

root@debianhp:~/beef_injection_framework# ruby shank.rb
/usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/ipaddr.rb:460:in `initialize': address family must be specified (ArgumentError)
        from shank.rb:114:in`new'
        from shank.rb:114:in `initialize'
        from shank.rb:284:in`new'
        from shank.rb:284:in `<main>'

can someone help me please?

**Comment by badatel** [comment]
I tryed this command aswell
 root@debianhp:~/beef_injection_framework# ruby shank.rb 192.168.0.100:80
/usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/ipaddr.rb:544:in `in6_addr': invalid address (ArgumentError)
        from /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/ipaddr.rb:481:in`initialize'
        from shank.rb:114:in `new'
        from shank.rb:114:in`initialize'
        from shank.rb:284:in `new'
        from shank.rb:284:in`<main>'

MORE INFORMATION:
root@debianhp:~/beef_injection_framework# gem env
RubyGems Environment:
- RUBYGEMS VERSION: 2.2.2
- RUBY VERSION: 1.9.3 (2014-02-24 patchlevel 545) [i686-linux]
- INSTALLATION DIRECTORY: /usr/local/rvm/gems/ruby-1.9.3-p545
- RUBY EXECUTABLE: /usr/local/rvm/rubies/ruby-1.9.3-p545/bin/ruby
- EXECUTABLE DIRECTORY: /usr/local/rvm/gems/ruby-1.9.3-p545/bin
- SPEC CACHE DIRECTORY: /root/.gem/specs
- RUBYGEMS PLATFORMS:
  - ruby
  - x86-linux
- GEM PATHS:
  - /usr/local/rvm/gems/ruby-1.9.3-p545
  - /usr/local/rvm/gems/ruby-1.9.3-p545@global
- GEM CONFIGURATION:
  - :update_sources => true
  - :verbose => true
  - :backtrace => false
  - :bulk_threshold => 1000
- REMOTE SOURCES:
  - https://rubygems.org/
- SHELL PATH:
  - /usr/local/rvm/gems/ruby-1.9.3-p545/bin
  - /usr/local/rvm/gems/ruby-1.9.3-p545@global/bin
  - /usr/local/rvm/rubies/ruby-1.9.3-p545/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/local/rvm/bin

root@debianhp:~/beef_injection_framework# gem list

**\* LOCAL GEMS ***

addressable (2.3.6)
ansi (1.4.3)
bigdecimal (1.1.0)
bundler (1.6.2)
daemons (1.1.9)
data_objects (0.10.14)
dm-core (1.2.1)
dm-do-adapter (1.2.0)
dm-migrations (1.2.0)
dm-sqlite-adapter (1.2.0)
do_sqlite3 (0.10.14)
em-websocket (0.3.8)
erubis (2.7.0)
eventmachine (1.0.3)
execjs (2.0.2)
file-tail (1.0.11)
gem-wrappers (1.2.4)
geoip (1.4.0)
io-console (0.3)
json (1.8.1, 1.5.5)
librex (0.0.68)
libv8 (3.16.14.3)
mime-types (2.2)
minitest (2.5.1)
msfrpc-client (1.0.1)
msgpack (0.5.8)
multi_json (1.9.2)
netrc (0.7.7)
packetfu (1.1.10)
parseconfig (1.0.4)
rack (1.5.2)
rack-protection (1.5.3)
rainbow (2.0.0)
rake (0.9.2.2)
rdoc (3.9.5)
ref (1.0.5)
rest-client (1.6.7)
rest_client (1.7.3)
rexec (1.6.3)
ruby2ruby (2.1.0)
ruby_parser (3.6.0)
rubydns (0.7.3)
rubyzip (1.1.3)
rvm (1.11.3.9)
sexp_processor (4.4.3)
sinatra (1.4.2)
sourcify (0.5.0)
term-ansicolor (1.1.5)
therubyracer (0.12.1)
thin (1.6.2)
tilt (1.4.1)
tins (0.5.6)
uglifier (2.2.1)

root@debianhp:~/beef_injection_framework# ruby -rpp -e "pp $:"
["/usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1",
 "/usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/i686-linux",
 "/usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby",
 "/usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/vendor_ruby/1.9.1",
 "/usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/vendor_ruby/1.9.1/i686-linux",
 "/usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/vendor_ruby",
 "/usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1",
 "/usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/i686-linux"]
